name: "Incremental GitHub Sync"

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      TARGET_ORG: ""
      REPO_NAME: ""
      SOURCE_ORG: MGMResorts
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Run Sync Script
        env:
          GITHUB_SOURCE_TOKEN: ${{ secrets.SOURCE_ADMIN_TOKEN }}
          GITHUB_DEST_TOKEN: ${{ secrets.TARGET_ADMIN_TOKEN }}
        run: |
          # echo "REPO_NAME=booking-room-resv-addons" >> $GITHUB_ENV
          bash ./.github/scripts/github_migrate.sh
