name: "Use Workflow Setup"
description: "Enter details for GitHub organization and token"
title: "[WORKFLOW SETUP]"
labels: ["automation", "setup"]
body:
  - type: input
    id: org_name
    attributes:
      label: "Enter the GitHub organization name"
      description: "The name of your GitHub organization"
      placeholder: "e.g., my-org"

  - type: textarea
    id: token
    attributes:
      label: "Enter your GitHub token"
      description: "Your GitHub personal access token (ensure it has 'repo' and 'workflow' scopes)"
      placeholder: "ghp_XXXXXXXXXXXXXXXXXXXX"

  - type: markdown
    attributes:
      value: |
        **Note**: Ensure your token has the necessary permissions. Do not share your token publicly.
