name: "Upload File Request"
description: "Upload a file and provide relevant details."
title: "[Upload Request] - "
labels: ["upload", "file"]
body:
  - type: markdown
    attributes:
      value: |
        **Attach the file to this issue using GitHub’s file upload feature.**  
        Drag and drop the file here or click to upload.

  - type: input
    id: file_description
    attributes:
      label: "File Description"
      description: "Describe the contents and purpose of the uploaded file."
      placeholder: "Example: Log file for debugging..."
    validations:
      required: true

  - type: textarea
    id: additional_info
    attributes:
      label: "Additional Information"
      description: "Provide any extra details related to this upload request."
      placeholder: "Additional context about the file..."
