name: JFrog Xray Indexing Request
description: Request to create JF Xray indexing using a build name
title: "[Xray Indexing] Request for {{ build_name }}"
labels: ["xray", "indexing", "jfrog"]
assignees:
  - your-gh-username

body:
  - type: input
    id: build_name
    attributes:
      label: Build Name
      description: "Enter the name of the build as pushed to JFrog (e.g., `my-app-main-123`)"
      placeholder: "e.g., my-flutter-webapp-main-42"
    validations:
      required: true

  - type: input
    id: jfrog_project
    attributes:
      label: JFrog Project Key
      description: "Enter the JFrog project key (e.g., `my-jfrog-project`)"
      placeholder: "e.g., commerce"
    validations:
      required: true

  - type: input
    id: indexing_repo
    attributes:
      label: Target Repository (Optional)
      description: "Specify if indexing should be limited to a specific repo (optional)"
      placeholder: "e.g., my-npm-virtual"
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes or Context
      description: "Provide any extra details, links to workflows, or context as needed"
      placeholder: |
        This indexing request is for release bundle validation...
        Workflow link: https://github.com/org/repo/actions/runs/1234567890
    validations:
      required: false
