name: Azure DevOps to GitHub Migration

on:
  workflow_dispatch:

jobs:
  migrate-repo:
    runs-on: ubuntu-latest

    env:
      GH_PAT: ${{ secrets.GH_PAT }}
      ADO_PAT: ${{ secrets.AZURE_PAT }}
      ADO_ORG: "MGMResortsDigitalEngineering"
      ADO_TEAM_PROJECT: "_git"
      ADO_REPO: "mgm-commons"
      GITHUB_ORG: "test-git-actions"
      GITHUB_REPO: "mgm-commons"

    steps:
    - name: Checkout repository (optional)
      uses: actions/checkout@v4

    - name: Install GitHub CLI
      run: |
        sudo apt update
        sudo apt install -y gh
        gh --version

    - name: Install ADO2GH CLI Extension
      env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
      run: |
        gh extension install github/gh-ado2gh
        gh ado2gh --help

    - name: List all Azure DevOps Projects, Teams, and Repos
      env:
        ADO_ORG: MGMResortsDigitalEngineering
        ADO_PAT: ${{ secrets.ADO_PAT }}
      run: |
        echo "Fetching all projects, teams, and repositories in Azure DevOps org: ${ADO_ORG}"
    
        BASE_URL="https://dev.azure.com/${ADO_ORG}"
        AUTH_HEADER="-u :${ADO_PAT}"
    
        # Fetch all projects
        echo "Fetching projects..."
        PROJECTS=$(curl -s $AUTH_HEADER "$BASE_URL/_apis/projects?api-version=7.1-preview.1" | jq -r '.value[].name')
    
        for PROJECT in $PROJECTS; do
          echo ""
          echo "🔷 Project: $PROJECT"
    
          # Fetch teams for the project
          echo "  📁 Teams:"
          curl -s $AUTH_HEADER "$BASE_URL/$PROJECT/_apis/teams?api-version=7.1-preview.1" \
            | jq -r '.value[] | "    • \(.name)"'
    
          # Fetch repos for the project
          echo "  📂 Repositories:"
          curl -s $AUTH_HEADER "$BASE_URL/$PROJECT/_apis/git/repositories?api-version=7.1-preview.1" \
            | jq -r '.value[] | "    • \(.name) - \(.webUrl)"'
        done



    - name: Migrate repository from ADO to GitHub
      run: |
        echo "Starting migration from Azure DevOps to GitHub..."

        # 🔥 Fix: prevent GH_TOKEN from interfering with authentication
        unset GH_TOKEN
        
        # ✅ Authenticate with GH_PAT
        echo "${GH_PAT}" | gh auth login --with-token
        
        echo "Authenticated..."
        
        # ✅ Run migration with verbose logging
        gh ado2gh migrate-repo \
          --ado-org "${ADO_ORG}" \
          --ado-team-project "${ADO_TEAM_PROJECT}" \
          --ado-repo "${ADO_REPO}" \
          --github-org "${GITHUB_ORG}" \
          --github-repo "${GITHUB_REPO}" \
          --verbose


    - name: Migration complete
      run: echo "Migration finished. Please validate manually."
