name: Azure DevOps to GitHub Migration

on:
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  actions: write
  pull-requests: write

jobs:
  migrate-repo:
    runs-on: ubuntu-latest

    env:
      GH_PAT: ${{ secrets.GH_PAT }}
      ADO_PAT: ${{ secrets.ADO_PAT }}
      ADO_ORG: "prashantkum26"
      ADO_TEAM_PROJECT: "MyTestProject1"
      ADO_REPO: "TestRepo1"
      GITHUB_ORG: "test-git-actions"
      GITHUB_REPO: "TestRepo1"

    steps:
    - name: Checkout repository (optional)
      uses: actions/checkout@v4

    - name: Install GitHub CLI
      run: |
        sudo apt update
        sudo apt install -y gh
        gh --version

    - name: Install ADO2GH CLI Extension
      env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
      run: |
        gh extension install github/gh-ado2gh
        gh ado2gh --help

    - name: Validate Azure DevOps PAT
      continue-on-error: true 
      env:
        AZURE_DEVOPS_TOKEN: "${{ secrets.ADO_PAT }}"
        AZURE_DEVOPS_ORG: "${{ env.ADO_ORG }}"
      run: |
        echo "Validating Azure DevOps PAT..."

        response=$(curl -s -o /dev/null -w "%{http_code}" -u ":${AZURE_DEVOPS_TOKEN}" \
          "https://dev.azure.com/prashantkum26/_apis/projects?api-version=7.1-preview.1")

        
        if [[ "$response" -ne 200 ]]; then
          echo "Error: Azure DevOps PAT is invalid or does not have the required permissions. Response code: $response"
          exit 1
        else
          echo "Azure DevOps PAT is valid."
        fi

    - name: Generate and print migration script
      run: |
        gh ado2gh generate-script \
          --ado-org "${ADO_ORG}" \
          --ado-team-project "${ADO_TEAM_PROJECT}" \
          --github-org "${GITHUB_ORG}" \
          --output migration-script.sh --verbose
    
        echo "✅ Migration script generated: migration-script.sh"
        echo "🔍 Printing script contents:"
        echo "--------------------------------------------"
        cat migration-script.sh
        echo "--------------------------------------------"


    # - name: Install Azure CLI
    #   run: |
    #     curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    
    # - name: Install Azure DevOps extension for Azure CLI
    #   run: |
    #     az extension add --name azure-devops || echo "Extension already installed"
    
    # - name: Validate Azure DevOps PAT
    #   continue-on-error: true
    #   env:
    #     AZURE_DEVOPS_EXT_PAT: ${{ secrets.ADO_PAT }}
    #   run: |
    #     az devops configure --defaults organization=https://dev.azure.com/${{ env.ADO_ORG }}
    #     if az devops project list --output none; then
    #       echo "Azure DevOps PAT is valid."
    #     else
    #       echo "Invalid Azure DevOps PAT or insufficient permissions."
    #       exit 1
    #     fi

    - name: Migrate repository from ADO to GitHub
      run: |
        echo "Starting migration from Azure DevOps to GitHub..."

        # 🔥 Fix: prevent GH_TOKEN from interfering with authentication
        unset GH_TOKEN
        
        # ✅ Authenticate with GH_PAT
        echo "${GH_PAT}" | gh auth login --with-token
        
        echo "Authenticated..."
        
        # ✅ Run migration with verbose logging
        gh ado2gh migrate-repo \
          --ado-org "${ADO_ORG}" \
          --ado-team-project "${ADO_TEAM_PROJECT}" \
          --ado-repo "${ADO_REPO}" \
          --github-org "${GITHUB_ORG}" \
          --github-repo "${GITHUB_REPO}" \
          --verbose

    - name: Migration complete
      run: echo "Migration finished. Please validate manually."
