name: Azure DevOps to GitHub Migration

on:
  workflow_dispatch:

jobs:
  migrate-repo:
    runs-on: ubuntu-latest

    env:
      GH_PAT: ${{ secrets.GH_PAT }}
      ADO_PAT: ${{ secrets.AZURE_PAT }}
      ADO_ORG: "MGMResortsDigitalEngineering"
      ADO_TEAM_PROJECT: "Digital Ventures"
      ADO_REPO: "mgm-commons"
      GITHUB_ORG: "test-git-actions"
      GITHUB_REPO: "mgm-commons"

    steps:
    - name: Checkout repository (optional)
      uses: actions/checkout@v4

    - name: Install GitHub CLI
      run: |
        sudo apt update
        sudo apt install -y gh
        gh --version

    - name: Install ADO2GH CLI Extension
      env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
      run: |
        gh extension install github/gh-ado2gh
        gh ado2gh --help

    - name: Migrate repository from ADO to GitHub
      run: |
        echo "Starting migration from Azure DevOps to GitHub..."

        # 🔥 Fix: prevent GH_TOKEN from interfering with authentication
        unset GH_TOKEN
        
        # ✅ Authenticate with GH_PAT
        echo "${GH_PAT}" | gh auth login --with-token
        
        echo "Authenticated..."
        
        # ✅ Run migration with verbose logging
        gh ado2gh migrate-repo \
          --ado-org "${ADO_ORG}" \
          --ado-team-project "${ADO_TEAM_PROJECT}" \
          --ado-repo "${ADO_REPO}" \
          --github-org "${GITHUB_ORG}" \
          --github-repo "${GITHUB_REPO}" \
          --verbose


    - name: Migration complete
      run: echo "Migration finished. Please validate manually."
