name: Continuous Integration (af)
run-name: "(CI) - ${{ github.event.head_commit.message }}"

on:
  push:
    branches:
      - "SSDLC-mgm_analytics"

jobs:
  ci:
    uses: "test-git-actions/test-1/.github/workflows/blank.yml@fcd2b98bd1dcabaf55a5020d5c7888a0a39d77e7"
    secrets: inherit
    with:
      version: "fcd2b98bd1dcabaf55a5020d5c7888a0a39d77e7"
      flutter_version: "3.0.2"
      flutter_channel: "stable"
      projectType: "flutter"
