name: Continuous Integration (af)
run-name: "(CI) - ${{ github.event.head_commit.message }}"

on:
  push:
    branches:
      - "SSDLC-mgm_analytics"

jobs:
  ci:
    uses: "MGMResorts/mgm-af-ci-workflows/.github/workflows/reusable-ci.yml@00cb30d0f29014df88bab02cbe8bb9dd61d7d402"
    secrets: inherit
    with:
      version: "00cb30d0f29014df88bab02cbe8bb9dd61d7d402"
      flutter_version: "3.0.2"
      flutter_channel: "stable"
