name: Common Issue Event Receiver

on:
  issue_comment:
    types: [created]
  issues:
    types: [opened, edited]

permissions:
  contents: write
  issues: write
  actions: write
  pull-requests: write
  
jobs:
  # dispatch-incremental-push:
  #   if: contains(github.event.issue.labels.*.name, 'incremental-push')
  #   uses: ./.github/workflows/run-incremental-push.yml
  #   secrets: inherit

  # dispatch-xray-indexing:
  #   if: contains(github.event.issue.labels.*.name, 'xray-indexing')
  #   uses: ./.github/workflows/xray-indexing.yml
  #   secrets: inherit

  dispatch-oidc-mapping:
    if: contains(github.event.issue.labels.*.name, 'oidc-mapping')
    uses: ./.github/workflows/oidc-mapping.yml
    secrets: inherit
