name: Common Issue Event Receiver

on:
  issue_comment:
    types: [created]
  issues:
    types: [opened, edited]

permissions:
  contents: write
  issues: write
  actions: write
  pull-requests: write
  workflows: write

jobs:
  dispatch-incremental-push:
    if: contains(github.event.issue.labels.*.name, 'incremental-push')
    uses: ./.github/workflows/run-incremental-push.yml
    secrets: inherit
