name: "Extract Org and Token"
on:
  issues:
    types: [opened, edited]

jobs:
  extract-and-print:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Extract org name and token using GitHub Script
      - name: Extract Org and Token
        id: extract_data
        uses: actions/github-script@v6
        with:
          script: |
            const issueBody = context.payload.issue.body;
            
            // Extract org name and token from the issue body using regex
            const orgNameMatch = issueBody.match(/Enter the GitHub organization name:\s*\n*(.*)/);
            const tokenMatch = issueBody.match(/Enter your GitHub token:\s*\n*(.*)/);

            const orgName = orgNameMatch ? orgNameMatch[1].trim() : "";
            const token = tokenMatch ? tokenMatch[1].trim() : "";

            core.setOutput("org_name", orgName);
            core.setOutput("token", token);

      # Step 2: Print extracted values
      - name: Print extracted values
        run: |
          echo "Organization: ${{ steps.extract_data.outputs.org_name }}"
          echo "Token: ${{ steps.extract_data.outputs.token }}"
        env:
          ORG_NAME: ${{ steps.extract_data.outputs.org_name }}
          TOKEN: ${{ steps.extract_data.outputs.token }}
