name: "Incremental GitHub Sync - test"

on:
  schedule:
    - cron: "*/10 * * * *"
  repository_dispatch:
    types: [incremental-push-job]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: "Incremental GitHub Sync - test"
        uses: actions/checkout@v4

      - name: "Incremental GitHub Sync - test"
        run: |
          echo "Target Organization: ${{ github.event.client_payload.target_org }}"
          echo "Repository Name: ${{ github.event.client_payload.repo_name }}"
          
      - name: "Incremental GitHub Sync - test"
        env:
          GITHUB_SOURCE_TOKEN: ${{ secrets.GH_PAT }}
          GITHUB_DEST_TOKEN: ${{ secrets.GH_PAT }}
          TARGET_ORG: ${{ github.event.client_payload.target_org }}
          REPO_NAME: ${{ github.event.client_payload.repo_name }}
          SOURCE_ORG: test-git-actions
        run: |
          bash ./.github/scripts/github_migrate.sh
