name: "Incremental GitHub Sync"

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      TARGET_ORG: ""
      REPO_NAME: ""
      SOURCE_ORG: ""
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Run Sync Script
        env:
          GITHUB_SOURCE_TOKEN: ${{ secrets.GH_PAT }}
          GITHUB_DEST_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          bash ./.github/scripts/github_migrate.sh
