name: "Incremental GitHub Sync - test-1"

on:
  schedule:
    - cron: "*/2 * * * *"
  workflow_dispatch:
    inputs:
        target_org:
          description: 'Target Organization'
          required: true
          default: 'mgmri-commerce'
        repo_name:
          description: 'Repository Name'
          required: true
          default: 'example-repo'
        source_org:
          description: 'Repository Name'
          required: true
          default: 'MGMResorts'
          
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout action"
        uses: actions/checkout@v4

      - name: "Print the client payload"
        run: |
          echo "Target Organization: ${{ github.event.inputs.target_org }}"
          echo "Repository Name: ${{ github.event.inputs.repo_name }}"
          
      - name: Run Sync Script
        env:
          GITHUB_SOURCE_TOKEN: ${{ secrets.GH_PAT }}
          GITHUB_DEST_TOKEN: ${{ secrets.GH_PAT }}
          TARGET_ORG: ${{ github.event.inputs.target_org }}
          REPO_NAME: ${{ github.event.inputs.repo_name }}
          SOURCE_ORG: test-git-actions
        run: |
          bash ./.github/scripts/github_migrate.sh
