name: "Incremental GitHub Sync - test - (*)"

on:
  schedule:
    - cron: "*"  # Runs once every 24 hours
  workflow_dispatch:  # Allows manual execution
  repository_dispatch:
    types: [incremental-push-job]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: "Incremental GitHub Sync - test - (*)"
        uses: actions/checkout@v4

      # - name: "Incremental GitHub Sync - test - (*)"
      #   env:
      #     GITHUB_SOURCE_TOKEN: ${{ secrets.GITHUB_SOURCE_TOKEN }}
      #     GITHUB_DEST_TOKEN: ${{ secrets.GITHUB_DEST_TOKEN }}
      #   run: |
      #     bash ./.github/scipts/github_migrate.sh
