name: Run Incremental Push

on:
  workflow_call:

permissions:
  contents: write
  actions: write
  pull-requests: write

jobs:
  secrets_variables_migration:
    runs-on: ubuntu-latest
    steps:
      - name: Check out scripts
        uses: actions/checkout@v3

      - name: Parse issue body
        id: parse-issue-body
        uses: stefanbuck/github-issue-parser@v3

      - run: echo $JSON_STRING
        env:
          JSON_STRING: ${{ steps.parse-issue-body.outputs.jsonString }}

      - name: Run Incremental Push
        uses: peter-evans/repository-dispatch@v1
        with:
            event-type: incremental-push
            client-payload: |
                {
                  "src_org": "MGMResorts",
                  "target_org": "${{ fromJson(steps.parse-issue-body.outputs.jsonString).target_organization }}",
                  "repo_name": "${{ fromJson(steps.parse-issue-body.outputs.jsonString).repository_name }}",
                  "schedule_duration": "${{ fromJson(steps.parse-issue-body.outputs.jsonString).schedule_duration }}"
                }

            
            

