name: Run Incremental Push

on:
  workflow_call:

permissions:
  contents: write
  actions: write
  pull-requests: write
  issues: write

jobs:
  secrets_variables_migration:
    runs-on: ubuntu-latest
    steps:
      - name: Check out scripts
        uses: actions/checkout@v3

      - name: Parse issue body
        id: parse-issue-body
        uses: stefanbuck/github-issue-parser@v3

      - run: echo $JSON_STRING
        env:
          JSON_STRING: ${{ steps.parse-issue-body.outputs.jsonString }}

      - name: Extract Schedule Cron Expression
        id: extract-cron
        run: |
          case "${{ github.event.client_payload.schedule_duration || github.event.inputs.schedule_duration }}" in
            "2 minutes")   CRON="*/2 * * * *" ;;
            "10 minutes")  CRON="*/10 * * * *" ;;
            "30 minutes")  CRON="*/30 * * * *" ;;
            "60 minutes")  CRON="0 * * * *" ;;  # Every hour
            "2 hours")     CRON="0 */2 * * *" ;;
            "4 hours")     CRON="0 */4 * * *" ;;
            "8 hours")     CRON="0 */8 * * *" ;;
            "24 hours")    CRON="0 0 * * *" ;;  # Midnight every day
            *)             CRON="*" ;;  # Default to every second
          esac
          echo "CRON=$CRON" >> $GITHUB_ENV

      - name: Modify Workflow File
        run: |
          sed -i "s/cron: \".*\"/cron: \"${{ env.CRON }}\"/" .github/workflows/incremental-sync-job.yml
          sed -i "s/name: .*/name: \"Incremental GitHub Sync - ${{ fromJson(steps.parse-issue-body.outputs.jsonString).repository_name }} - (${{ env.CRON }})\"/" .github/workflows/incremental-sync-job.yml

      - name: Commit and Push Changes
        env:
          GH_PAT: ${{ secrets.PAT }}
        run: |
           git config --global user.name "github-actions[bot]"
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
           git pull
           git add .github/workflows/incremental-sync-job.yml || git add .
           git commit -m "Updated cron schedule to ${{ github.event.inputs.new_cron }}"
           git push

      - name: Schedule the Job - Incremental Push
        uses: peter-evans/repository-dispatch@v1
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            event-type: incremental-push-job
            client-payload: |
                {
                  "src_org": "MGMResorts",
                  "target_org": "${{ fromJson(steps.parse-issue-body.outputs.jsonString).target_organization }}",
                  "repo_name": "${{ fromJson(steps.parse-issue-body.outputs.jsonString).repository_name }}",
                  "schedule_duration": "${{ fromJson(steps.parse-issue-body.outputs.jsonString).schedule_duration }}"
                }

      # - name: Run Incremental Push
      #   uses: peter-evans/repository-dispatch@v1
      #   with:
      #       token: ${{ secrets.GITHUB_TOKEN }}
      #       event-type: incremental-push
      #       client-payload: |
      #           {
      #             "src_org": "MGMResorts",
      #             "target_org": "${{ fromJson(steps.parse-issue-body.outputs.jsonString).target_organization }}",
      #             "repo_name": "${{ fromJson(steps.parse-issue-body.outputs.jsonString).repository_name }}",
      #             "schedule_duration": "${{ fromJson(steps.parse-issue-body.outputs.jsonString).schedule_duration }}"
      #           }

            
            

