name: Run Python Script on Push

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.PAT }}

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 2: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas tabulate

      # Step 3: Run the Python script
      - name: Fetch and process workflow data
        run: |
          python - <<'EOF'
          import requests
          import pandas as pd
          import os
          from tabulate import tabulate

          def workflow_run():
              auth = f"Bearer {os.getenv('GITHUB_TOKEN')}"
              url = "https://api.github.com/repos/MGMResorts/mgm-af-migrations-via-actions/actions/workflows/110635589/runs?per_page=200"
              headers = {
                  'Accept': 'application/vnd.github+json',
                  'Authorization': auth,
                  'X-GitHub-Api-Version': '2022-11-28'
              }
              response = requests.get(url, headers=headers)
              
              if response.status_code != 200:
                  print(f"Failed to fetch data: {response.status_code} - {response.text}")
                  return

              runs = response.json().get('workflow_runs', [])
              total_runs = len(runs)

              if total_runs == 0:
                  print("No workflow runs found.")
                  return

              data = []
              for idx, run in enumerate(runs, start=1):
                  data.append({
                      'Serial No.': idx,
                      'Id': f"<a href='{run['html_url']}' target='_blank'>{run['id']}</a>",
                      'Name': run['name'],
                      'Branch': run['head_branch'],
                      'Run Number': run['run_number'],
                      'Status': run['status'],
                      'Conclusion': run['conclusion'],
                      'Actor': run['actor']['login'] if run.get('actor') else 'N/A',
                  })

              df = pd.DataFrame(data)
              df.to_csv("workflow_runs.csv", sep='\t', index=False)

              page_size = 20
              total_pages = (total_runs + page_size - 1) // page_size

              with open("summary.md", "w") as summary_file:
                  summary_file.write("# Workflow Runs Summary\n\n")
                  summary_file.write(f"**Total Workflow Runs: {total_runs}**\n\n")
                  for page in range(total_pages):
                      start = page * page_size
                      end = min(start + page_size, total_runs)
                      markdown_table = tabulate(
                          df.iloc[start:end],
                          headers="keys",
                          tablefmt="github",
                          showindex=False
                      )
                      summary_file.write(f"### Page {page + 1}\n\n")
                      summary_file.write(markdown_table + "\n\n")

          if __name__ == "__main__":
              try:
                  workflow_run()
                  print("Data fetched and summary generated successfully")
              except Exception as e:
                  print(f"Error: {e}")
          EOF

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 4: Check if summary.md exists
      - name: Check if summary.md exists
        run: |
          if [ ! -f "summary.md" ]; then
            echo "Error: summary.md was not created."
            exit 1
          fi

      # Step 5: Add summary to workflow
      - name: Add summary to workflow
        run: cat summary.md >> $GITHUB_STEP_SUMMARY

      # Step 6: Upload the CSV as an artifact
      - name: Upload workflow_runs.csv
        uses: actions/upload-artifact@v4
        with:
          name: workflow-runs
          path: workflow_runs.csv
