name: Repositories Migration to GHEC [GEI]

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  issues: write

jobs:
  migrate:
    uses: ./.github/workflows/shared-github-enterprise-cloud-gei.yml
        
